context:
  version: 0.9.0

package:
  name: dockerfile-language-server-nodejs
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/dockerfile-language-server-nodejs/-/dockerfile-language-server-nodejs-${{ version }}.tgz
  sha256: 88a6085ca049ebdf383f3644ee699e982379e3767918bf14baedd0ef90c1e18f

build:
  number: 0
  noarch: generic

requirements:
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - "docker-langserver 2>&1 | grep -q \"Connection input stream is not set.\""

about:
  license: MIT
  license_file:
    - License.txt
    - third-party-licenses.txt
  summary: A language server for Dockerfiles powered by Node.js, TypeScript, and VSCode technologies
  homepage: https://github.com/rcjsuen/dockerfile-language-server-nodejs
  repository: https://github.com/rcjsuen/dockerfile-language-server-nodejs

extra:
  recipe-maintainers:
    - danielnachun
